"""Add products attributes and specifications JSONB columns and AI analytics models

Revision ID: 31c8822fe40c
Revises: 
Create Date: 2026-09-25 15:11:59.588806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31c8822fe40c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('activity_logs_profile_id_fkey', 'activity_logs', type_='foreignkey')
    op.create_foreign_key(None, 'activity_logs', 'profiles', ['profile_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint('addresses_profile_id_fkey', 'addresses', type_='foreignkey')
    op.create_foreign_key(None, 'addresses', 'profiles', ['profile_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('cart_items_cart_id_product_id_key', 'cart_items', type_='unique')
    op.create_unique_constraint('uq_cart_product', 'cart_items', ['cart_id', 'product_id'], schema='public')
    op.drop_constraint('cart_items_cart_id_fkey', 'cart_items', type_='foreignkey')
    op.drop_constraint('cart_items_product_id_fkey', 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'carts', ['cart_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'cart_items', 'products', ['product_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('carts_id_fkey', 'carts', type_='foreignkey')
    op.create_foreign_key(None, 'carts', 'profiles', ['id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('categories_slug_key', 'categories', type_='unique')
    op.create_index(op.f('ix_public_categories_id'), 'categories', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_categories_slug'), 'categories', ['slug'], unique=True, schema='public')
    op.drop_constraint('categories_parent_id_fkey', 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint('conversational_sessions_profile_id_fkey', 'conversational_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'conversational_sessions', 'profiles', ['profile_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.alter_column('coupons', 'discount_type',
               existing_type=postgresql.ENUM('percentage', 'fixed', name='discount_type'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_constraint('coupons_code_key', 'coupons', type_='unique')
    op.create_index(op.f('ix_public_coupons_code'), 'coupons', ['code'], unique=True, schema='public')
    op.drop_constraint('inventory_product_id_fkey', 'inventory', type_='foreignkey')
    op.create_foreign_key(None, 'inventory', 'products', ['product_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('notifications_profile_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'profiles', ['profile_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('order_items_product_id_fkey', 'order_items', type_='foreignkey')
    op.drop_constraint('order_items_order_id_fkey', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'shipped', 'delivered', 'cancelled', name='order_status'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::order_status"))
    op.drop_constraint('orders_billing_address_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_shipping_address_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_coupon_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_profile_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'coupons', ['coupon_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'addresses', ['shipping_address_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'profiles', ['profile_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'addresses', ['billing_address_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.alter_column('payments', 'provider',
               existing_type=postgresql.ENUM('stripe', 'paypal', 'razorpay', 'cod', name='payment_provider'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('pending', 'paid', 'failed', 'refunded', name='payment_status'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::payment_status"))
    op.drop_constraint('payments_order_id_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'orders', ['order_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('product_images_product_id_fkey', 'product_images', type_='foreignkey')
    op.create_foreign_key(None, 'product_images', 'products', ['product_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.alter_column('products', 'status',
               existing_type=postgresql.ENUM('draft', 'published', 'out_of_stock', name='product_status'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::product_status"))
    op.alter_column('products', 'attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('products', 'specifications',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint('products_sku_key', 'products', type_='unique')
    op.drop_constraint('products_slug_key', 'products', type_='unique')
    op.create_index(op.f('ix_public_products_sku'), 'products', ['sku'], unique=True, schema='public')
    op.create_index(op.f('ix_public_products_slug'), 'products', ['slug'], unique=True, schema='public')
    op.drop_constraint('products_category_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.alter_column('profiles', 'role',
               existing_type=postgresql.ENUM('customer', 'admin', name='user_role'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'customer'::user_role"))
    op.drop_constraint('profiles_email_key', 'profiles', type_='unique')
    op.drop_constraint('profiles_phone_key', 'profiles', type_='unique')
    op.create_index(op.f('ix_public_profiles_email'), 'profiles', ['email'], unique=True, schema='public')
    op.create_index(op.f('ix_public_profiles_id'), 'profiles', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_profiles_phone'), 'profiles', ['phone'], unique=True, schema='public')
    op.drop_constraint('recently_viewed_profile_id_product_id_key', 'recently_viewed', type_='unique')
    op.create_unique_constraint('uq_profile_recently_viewed', 'recently_viewed', ['profile_id', 'product_id'], schema='public')
    op.drop_constraint('recently_viewed_profile_id_fkey', 'recently_viewed', type_='foreignkey')
    op.drop_constraint('recently_viewed_product_id_fkey', 'recently_viewed', type_='foreignkey')
    op.create_foreign_key(None, 'recently_viewed', 'products', ['product_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'recently_viewed', 'profiles', ['profile_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('reviews_profile_id_product_id_key', 'reviews', type_='unique')
    op.create_unique_constraint('uq_profile_product_review', 'reviews', ['profile_id', 'product_id'], schema='public')
    op.drop_constraint('reviews_profile_id_fkey', 'reviews', type_='foreignkey')
    op.drop_constraint('reviews_product_id_fkey', 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'products', ['product_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'profiles', ['profile_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('search_analytics_clicked_product_id_fkey', 'search_analytics', type_='foreignkey')
    op.create_foreign_key(None, 'search_analytics', 'products', ['clicked_product_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint('wishlists_profile_id_product_id_key', 'wishlists', type_='unique')
    op.create_unique_constraint('uq_profile_wishlist_product', 'wishlists', ['profile_id', 'product_id'], schema='public')
    op.drop_constraint('wishlists_product_id_fkey', 'wishlists', type_='foreignkey')
    op.drop_constraint('wishlists_profile_id_fkey', 'wishlists', type_='foreignkey')
    op.create_foreign_key(None, 'wishlists', 'profiles', ['profile_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'wishlists', 'products', ['product_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishlists', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'wishlists', schema='public', type_='foreignkey')
    op.create_foreign_key('wishlists_profile_id_fkey', 'wishlists', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('wishlists_product_id_fkey', 'wishlists', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_profile_wishlist_product', 'wishlists', schema='public', type_='unique')
    op.create_unique_constraint('wishlists_profile_id_product_id_key', 'wishlists', ['profile_id', 'product_id'])
    op.drop_constraint(None, 'search_analytics', schema='public', type_='foreignkey')
    op.create_foreign_key('search_analytics_clicked_product_id_fkey', 'search_analytics', 'products', ['clicked_product_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'reviews', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'reviews', schema='public', type_='foreignkey')
    op.create_foreign_key('reviews_product_id_fkey', 'reviews', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('reviews_profile_id_fkey', 'reviews', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_profile_product_review', 'reviews', schema='public', type_='unique')
    op.create_unique_constraint('reviews_profile_id_product_id_key', 'reviews', ['profile_id', 'product_id'])
    op.drop_constraint(None, 'recently_viewed', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'recently_viewed', schema='public', type_='foreignkey')
    op.create_foreign_key('recently_viewed_product_id_fkey', 'recently_viewed', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('recently_viewed_profile_id_fkey', 'recently_viewed', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_profile_recently_viewed', 'recently_viewed', schema='public', type_='unique')
    op.create_unique_constraint('recently_viewed_profile_id_product_id_key', 'recently_viewed', ['profile_id', 'product_id'])
    op.drop_index(op.f('ix_public_profiles_phone'), table_name='profiles', schema='public')
    op.drop_index(op.f('ix_public_profiles_id'), table_name='profiles', schema='public')
    op.drop_index(op.f('ix_public_profiles_email'), table_name='profiles', schema='public')
    op.create_unique_constraint('profiles_phone_key', 'profiles', ['phone'])
    op.create_unique_constraint('profiles_email_key', 'profiles', ['email'])
    op.alter_column('profiles', 'role',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('customer', 'admin', name='user_role'),
               existing_nullable=False,
               existing_server_default=sa.text("'customer'::user_role"))
    op.drop_constraint(None, 'products', schema='public', type_='foreignkey')
    op.create_foreign_key('products_category_id_fkey', 'products', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_public_products_slug'), table_name='products', schema='public')
    op.drop_index(op.f('ix_public_products_sku'), table_name='products', schema='public')
    op.create_unique_constraint('products_slug_key', 'products', ['slug'])
    op.create_unique_constraint('products_sku_key', 'products', ['sku'])
    op.alter_column('products', 'specifications',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('products', 'attributes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('products', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('draft', 'published', 'out_of_stock', name='product_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::product_status"))
    op.drop_constraint(None, 'product_images', schema='public', type_='foreignkey')
    op.create_foreign_key('product_images_product_id_fkey', 'product_images', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'payments', schema='public', type_='foreignkey')
    op.create_foreign_key('payments_order_id_fkey', 'payments', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.alter_column('payments', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('pending', 'paid', 'failed', 'refunded', name='payment_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::payment_status"))
    op.alter_column('payments', 'provider',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('stripe', 'paypal', 'razorpay', 'cod', name='payment_provider'),
               existing_nullable=False)
    op.drop_constraint(None, 'orders', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'orders', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'orders', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'orders', schema='public', type_='foreignkey')
    op.create_foreign_key('orders_profile_id_fkey', 'orders', 'profiles', ['profile_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('orders_coupon_id_fkey', 'orders', 'coupons', ['coupon_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('orders_shipping_address_id_fkey', 'orders', 'addresses', ['shipping_address_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('orders_billing_address_id_fkey', 'orders', 'addresses', ['billing_address_id'], ['id'], ondelete='SET NULL')
    op.alter_column('orders', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('pending', 'processing', 'shipped', 'delivered', 'cancelled', name='order_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::order_status"))
    op.drop_constraint(None, 'order_items', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'order_items', schema='public', type_='foreignkey')
    op.create_foreign_key('order_items_order_id_fkey', 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('order_items_product_id_fkey', 'order_items', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'notifications', schema='public', type_='foreignkey')
    op.create_foreign_key('notifications_profile_id_fkey', 'notifications', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'inventory', schema='public', type_='foreignkey')
    op.create_foreign_key('inventory_product_id_fkey', 'inventory', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_coupons_code'), table_name='coupons', schema='public')
    op.create_unique_constraint('coupons_code_key', 'coupons', ['code'])
    op.alter_column('coupons', 'discount_type',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('percentage', 'fixed', name='discount_type'),
               existing_nullable=False)
    op.drop_constraint(None, 'conversational_sessions', schema='public', type_='foreignkey')
    op.create_foreign_key('conversational_sessions_profile_id_fkey', 'conversational_sessions', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'categories', schema='public', type_='foreignkey')
    op.create_foreign_key('categories_parent_id_fkey', 'categories', 'categories', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_public_categories_slug'), table_name='categories', schema='public')
    op.drop_index(op.f('ix_public_categories_id'), table_name='categories', schema='public')
    op.create_unique_constraint('categories_slug_key', 'categories', ['slug'])
    op.drop_constraint(None, 'carts', schema='public', type_='foreignkey')
    op.create_foreign_key('carts_id_fkey', 'carts', 'profiles', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'cart_items', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'cart_items', schema='public', type_='foreignkey')
    op.create_foreign_key('cart_items_product_id_fkey', 'cart_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('cart_items_cart_id_fkey', 'cart_items', 'carts', ['cart_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_cart_product', 'cart_items', schema='public', type_='unique')
    op.create_unique_constraint('cart_items_cart_id_product_id_key', 'cart_items', ['cart_id', 'product_id'])
    op.drop_constraint(None, 'addresses', schema='public', type_='foreignkey')
    op.create_foreign_key('addresses_profile_id_fkey', 'addresses', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'activity_logs', schema='public', type_='foreignkey')
    op.create_foreign_key('activity_logs_profile_id_fkey', 'activity_logs', 'profiles', ['profile_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
